server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/tasktracker
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.kafka.bootstrap-servers=kafka:29093
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=emailMessage:com.tasktracker.backend.dto.EmailMessage
spring.kafka.producer.properties.spring.json.add.type.headers=true

spring.devtools.restart.enabled=false

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

my.spring.kafka.topic.name=EMAIL_SENDING_TASKS
my.secret.key=secret
