server.port=8080
# ===== DATABASE =====
spring.datasource.url=jdbc:postgresql://localhost:5432/tasktracker
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===== KAFKA =====
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=emailMessage:com.tasktracker.backend.dto.EmailMessage
spring.kafka.producer.properties.spring.json.add.type.headers=true

# ===== DEV =====
spring.devtools.restart.enabled=false